### ISSUE TITLE
Add support for multiple extensions per repo

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-extensions-store#11]
Requires change on these lines to point to a subfolder in a repo:
https://github.com/UnofficialCrusaderPatch/UCP3-extensions-store/blob/79e54ffc3223d5e3554a5e4d82b5346f37f08157/scripts/build-store.ps1#L238-L243

Example recipe
```yml
- definition:
    name: Legends-Of-The-Orient-AI
    version: 3.0.1
    type: plugin
  contents:
    source:
      method: github
      url: CrusaderPilaw/extension-Legends-of-the-Orient-AI
      github-sha: f9abda8a566b81c6d50382724f5f208f2e1a3202
      github-tag: main
      location: Legends-of-the-Orient-AI # Means use the folder named like this in the github repo.
```

New code
```pwsh

if ($source.location -ne $null) {
  $destination = "$($destination)\$($source.location)"
}

 if ($extension.definition.type -eq "module") { 
   & ".\build\ucp3\scripts\build-module.ps1" -Path $destination -Destination "$binaryDestination\" -BUILD_CONFIGURATION "ReleaseSecure" -UCPNuPkgPath "$NUPKG_DIRECTORY" -RemoveZippedFolders 
 } 
 else { 
   & ".\build\ucp3\scripts\build-plugin.ps1" -Path $destination -Destination "$binaryDestination" -RemoveZippedFolders -Zip 
 } 
```

**Comment by gynt** [comment]
Included but untested in 6894c2f15a3cd640346007d3e689670976ed0424

**Comment by Krarilotus** [comment]
```ps1
$definition = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$($source.url)/$($source['github-sha'])/definition.yml" |
  Select-Object -ExpandProperty Content | 
  ConvertFrom-Yaml
  ```
  can this maybe help? I tested it but it seemd to fail building the recipee.yml
  
  part of the recipee.yml
  ```yml
      - definition:
        name: Ascension-Multiplayer
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 72e961f1c051e8214c2ef041c38bb42c6f2de36a
          github-tag: ucp3-ascension
          location: extension-Ascension-Multiplayer
    - definition:
        name: Ascension-Maps
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 72e961f1c051e8214c2ef041c38bb42c6f2de36a
          github-tag: ucp3-ascension
          location: extension-Ascension-Maps
  ```
